title: vemek.co
email: blog@vemek.co
description: >-
  A blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vemek.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vemek
github_username:  vemek

# Build settings
theme: minima

plugins:
  - jekyll-postcss
