title: vemek.github.io
source:       .
destination:  ./_site
safe:         false
exclude:      [Gemfile, Gemfile.lock]
baseurl:      /
timezone:     Europe/Dublin
plugins:     ./_plugins
future:      false
lsi:         false
highlighter: pygments
permalink:   pretty

# Plugins
gems:
  - jekyll-index-generator
  - jekyll-mentions

jekyll-mentions: https://twitter.com
