title: vemek.co
source: .
destination: ./_site
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
safe: false
exclude: [Gemfile, Gemfile.lock]
baseurl: /
timezone: Europe/Dublin
future: false
lsi: false
permalink: pretty
incremental: false
highlighter: rouge
gist:
  noscript: false
plugin_dir: _plugins
